version: "2.3"
# simple docker compose to play with Elasticsearch & Kibana locally
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "network.host=127.0.0.1"
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "indices.id_field_data.enabled=true"
      - "xpack.license.self_generated.type=trial"
      - "xpack.security.enabled=false"
      - "ES_TEMP=/tmp"
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
volumes:
  data:
    driver: local
