name: pull-request-build

on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@master
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - name: Cache build .gradle dir
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle
          .gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
    - name: Compose up
      run: ./gradlew :search-client:composeUp
    - name: Gradle Build
      run: ./gradlew check
    - name: Compose down
      run: ./gradlew :search-client:composeDown
